print("*** STUDENT MARKS ***")
name= input("Enter The Student Name: ") 
rollno = input("Enter The Student Roll Number: ")
tel = int(input("Enter Telugu Marks: "))
hin = int(input("Enter Hindi Marks: "))
eng = int(input("Enter english Marks: "))
mat = int(input("Enter Maths Marks: "))
sci = int(input("Enter Science Marks: "))
soc= int(input("Enter Social Marks: "))
total=int(tel+hin+eng+mat+sci+soc)
per=float((total/600)*100)
print("Total Marks: ",total)
print("Percentage:",per)
